import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:frontend/models/pool_model.dart';
import 'package:frontend/models/expense_model.dart';
import 'package:frontend/providers/pool_providers.dart';
import 'package:frontend/providers/dashboard_controller.dart';
import 'package:frontend/services/pool_repository.dart';
import 'package:frontend/services/image_upload_service.dart';
import 'package:frontend/theme/design_tokens.dart';
import 'package:frontend/widgets/app_surface.dart';
import 'package:frontend/widgets/page_header.dart';
import 'package:frontend/widgets/page_scaffold.dart';

class LogExpenseScreen extends ConsumerStatefulWidget {
  final Pool pool;

  const LogExpenseScreen({super.key, required this.pool});

  @override
  ConsumerState<LogExpenseScreen> createState() => _LogExpenseScreenState();
}

class _LogExpenseScreenState extends ConsumerState<LogExpenseScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _amountController = TextEditingController();
  final _noteController = TextEditingController();
  
  String _selectedCategory = 'Other';
  DateTime _selectedDate = DateTime.now();
  File? _receiptImage;
  bool _isLoading = false;

  final List<String> _categories = ['Food', 'Transport', 'Supplies', 'Services', 'Other'];

  @override
  void dispose() {
    _titleController.dispose();
    _amountController.dispose();
    _noteController.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final date = await showDatePicker(
      context: context,
      initialDate: _selectedDate,
      firstDate: DateTime(2020),
      lastDate: DateTime.now(),
    );
    if (date != null) {
      setState(() => _selectedDate = date);
    }
  }

  Future<void> _pickImage() async {
    final file = await ImageUploadService.pickImageWithSource();
    if (file != null) {
      setState(() => _receiptImage = file);
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      String? receiptUrl;
      if (_receiptImage != null) {
        receiptUrl = await ImageUploadService.uploadImage(
          _receiptImage!,
          folder: 'expenses/${widget.pool.id}/${DateTime.now().millisecondsSinceEpoch}',
        );
      }

      final expense = Expense(
        id: '', // Generated by backend
        poolId: widget.pool.id,
        title: _titleController.text.trim(),
        amount: double.parse(_amountController.text.trim()),
        category: _selectedCategory,
        note: _noteController.text.trim(),
        receiptUrl: receiptUrl,
        createdBy: '', // Set by backend
        createdAt: _selectedDate,
      );

      await ref.read(poolRepositoryProvider).addExpense(
        poolId: widget.pool.id,
        expense: expense,
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Expense logged successfully!')),
        );
        ref.invalidate(dashboardControllerProvider);
        ref.invalidate(ledgerProvider(widget.pool.id));
        ref.invalidate(activityFeedProvider);
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error logging expense: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return PageScaffold(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          PageHeader(
            title: 'Log Expense',
            subtitle: 'Record money spent from the pool balance.',
            actions: [
              IconButton(
                style: IconButton.styleFrom(
                  backgroundColor: Theme.of(context).colorScheme.surfaceContainerHighest,
                  foregroundColor: Theme.of(context).colorScheme.onSurfaceVariant,
                  shape: const CircleBorder(),
                ),
                icon: const Icon(Icons.arrow_back_rounded),
                onPressed: () => Navigator.pop(context),
              ),
            ],
          ),
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.only(bottom: DesignTokens.space3Xl),
              child: AppSurface(
                elevation: 0,
                showOutline: true,
                padding: const EdgeInsets.all(DesignTokens.spaceXl),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      TextFormField(
                        controller: _titleController,
                        decoration: const InputDecoration(
                          labelText: 'Expense Title *',
                          hintText: 'e.g., Pizza Party',
                        ),
                        validator: (value) => 
                          value == null || value.trim().isEmpty ? 'Required' : null,
                      ),
                      const SizedBox(height: DesignTokens.spaceLg),
                      TextFormField(
                        controller: _amountController,
                        keyboardType: const TextInputType.numberWithOptions(decimal: true),
                        decoration: const InputDecoration(
                          labelText: 'Amount (₹) *',
                          prefixText: '₹ ',
                        ),
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) return 'Required';
                          final parsed = double.tryParse(value.trim());
                          if (parsed == null || parsed <= 0) return 'Enter a valid positive amount';
                          return null;
                        },
                      ),
                      const SizedBox(height: DesignTokens.spaceLg),
                      DropdownButtonFormField<String>(
                        initialValue: _selectedCategory,
                        decoration: const InputDecoration(labelText: 'Category'),
                        items: _categories.map((c) => DropdownMenuItem(
                          value: c, child: Text(c),
                        )).toList(),
                        onChanged: (val) {
                          if (val != null) {
                            setState(() => _selectedCategory = val);
                          }
                        },
                      ),
                      const SizedBox(height: DesignTokens.spaceLg),
                      InkWell(
                        onTap: _pickDate,
                        borderRadius: DesignTokens.radiusMd,
                        child: InputDecorator(
                          decoration: const InputDecoration(
                            labelText: 'Date',
                          ),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(DateFormat.yMMMd().format(_selectedDate)),
                              const Icon(Icons.calendar_today_rounded, size: 20),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: DesignTokens.spaceLg),
                      TextFormField(
                        controller: _noteController,
                        maxLines: 3,
                        decoration: const InputDecoration(
                          labelText: 'Notes (Optional)',
                          hintText: 'Any extra details about this expense...',
                        ),
                      ),
                      const SizedBox(height: DesignTokens.spaceLg),
                      const Text(
                        'Receipt Photo (Optional)',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                      const SizedBox(height: DesignTokens.spaceSm),
                      InkWell(
                        onTap: _pickImage,
                        borderRadius: DesignTokens.radiusMd,
                        child: Container(
                          height: 120,
                          width: double.infinity,
                          decoration: BoxDecoration(
                            border: Border.all(
                              color: Theme.of(context).colorScheme.outlineVariant,
                            ),
                            borderRadius: DesignTokens.radiusMd,
                          ),
                          child: _receiptImage != null
                              ? ClipRRect(
                                  borderRadius: DesignTokens.radiusMd,
                                  child: Image.file(_receiptImage!, fit: BoxFit.cover),
                                )
                              : Center(
                                  child: Column(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      Icon(Icons.add_a_photo_outlined, 
                                        color: Theme.of(context).colorScheme.onSurfaceVariant),
                                      const SizedBox(height: 8),
                                      Text(
                                        'Tap to add receipt',
                                        style: TextStyle(
                                          color: Theme.of(context).colorScheme.onSurfaceVariant,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                        ),
                      ),
                      const SizedBox(height: DesignTokens.space2Xl),
                      SizedBox(
                        width: double.infinity,
                        height: 56,
                        child: FilledButton(
                          onPressed: _isLoading ? null : _submit,
                          child: _isLoading 
                              ? const CircularProgressIndicator(color: Colors.white)
                              : const Text('Log Expense', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
